<?php

namespace AppBundle\Repository;

/**
 * ExpansionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpansionRepository extends \Doctrine\ORM\EntityRepository
{

}
