<?php

namespace AppBundle\Repository;

/**
 * PlayLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayLogRepository extends \Doctrine\ORM\EntityRepository
{
}
